name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # FIXME Use stable scala version
        scala: [2.13.11, 3.3.1-RC1-bin-20230318-7226ba6-NIGHTLY]

    steps:
      - uses: actions/checkout@v3

      - name: Cache jabba
        uses: actions/cache@v3.2.4
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jabba-cache-${{ hashFiles('**/workflows/scala.yml') }}

      - name: Cache SBT ivy cache
        uses: actions/cache@v3.2.4
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v3.2.4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - uses: olafurpg/setup-scala@v13
        with:
          java-version: graalvm@21.0.0=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-linux-amd64-21.0.0.tar.gz

      - name: Test
        run: sbt ++${{matrix.scala}} test
